/**
 * Parses a statute article body into renderable blocks.
 *
 * The prose lives in `messages/<locale>.json` as one string per article, so
 * translators work on a whole coherent article rather than disconnected
 * fragments. Blocks are separated by a blank line; a block whose every line is
 * a lettered item (`a) …`) becomes a list.
 *
 * Markers are STRIPPED and re-generated by the renderer, so paragraph numbers
 * and list letters stay identical across locales no matter how a translator
 * wrote them.
 */

export type StatutenBlock =
  | { kind: 'paragraph'; text: string }
  | { kind: 'list'; items: string[] }

/** `a) text` — the leading marker of a lettered sub-item. */
const LIST_ITEM = /^[a-z]\)\s+/

export function parseStatutenBody(body: string): StatutenBlock[] {
  return body
    .split('\n\n')
    .map(block => block.trim())
    .filter(Boolean)
    .map<StatutenBlock>(block => {
      const lines = block
        .split('\n')
        .map(line => line.trim())
        .filter(Boolean)

      if (lines.length > 0 && lines.every(line => LIST_ITEM.test(line))) {
        return { kind: 'list', items: lines.map(line => line.replace(LIST_ITEM, '')) }
      }

      // A paragraph may be soft-wrapped across lines; join it back into one.
      return { kind: 'paragraph', text: lines.join(' ') }
    })
}

/**
 * Legal paragraph numbering counts only paragraphs — interleaved lists belong
 * to the paragraph that introduces them and must not consume a number.
 */
export function numberParagraphs(
  blocks: readonly StatutenBlock[]
): Array<{ block: StatutenBlock; number: number | null }> {
  let counter = 0
  return blocks.map(block => {
    if (block.kind === 'paragraph') {
      counter += 1
      return { block, number: counter }
    }
    return { block, number: null }
  })
}
